---
title: "Project1"
date: "1/15/2017"
output: pdf_document
---

```{r, echo=F, message=F, warning=F}
setwd("~/Documents/Biostatistics/Collaboration II")
#setwd("~/Documents/BIOS7352/Project1")

totalData <- readRDS("dataForABP_CBF_2017-01-11.rds")
library(Hmisc)
library(knitr)

crvdata <- totalData[totalData$asl.reac.usable == 1 & 
                       totalData$enrolled.dx.factor != "Dementia",
                     c(1:18, 61, grep("asl.reac", names(totalData)),
                       grep("ma.", names(totalData)))]
names(crvdata) <- sub("asl.reac.", "", names(crvdata), fixed = TRUE)
names(crvdata) <- sub(".hct", "", names(crvdata), fixed = TRUE)
names(crvdata) <- sub(".factor", "", names(crvdata), fixed = TRUE)
names(crvdata) <- sub("turnal.systolic.diff.sleep.self.reported", ".sys.diff", 
                      names(crvdata), fixed = TRUE)
crvdata <- crvdata[crvdata$time.reading.indicator == 'Yes' &
                     !is.na(crvdata$time.reading.indicator),]

exclude <- totalData[!(totalData$map.id %in% crvdata$map.id),
                     c(1:18, 61, grep("asl.reac", names(totalData)),
                       grep("ma.", names(totalData)))]
names(exclude) <- sub("asl.reac.", "", names(exclude), fixed = TRUE)
names(exclude) <- sub(".hct", "", names(exclude), fixed = TRUE)
names(exclude) <- sub(".factor", "", names(exclude), fixed = TRUE)
names(exclude) <- sub(".factor", "", names(exclude), fixed = TRUE)
names(exclude) <- sub("turnal.systolic.diff.sleep.self.reported", ".sys.diff", 
                      names(exclude), fixed = TRUE)
names(crvdata$noc.sys.diff)


#describe(crvdata)

#totalData$asl.reac.usable == 1,
                     

cats <- names(crvdata)[2:18]
comparison <- c(c(), c(), c(),c())
is <- length(crvdata$map.id)
xs <- length(exclude$map.id)
for (cat in cats){
  if (is.factor(crvdata[,cat])){
    chiData <- rbind(cbind(crvdata[,cat],rep("is", length(crvdata[,cat]))),
                     cbind(exclude[,cat],rep("xs", length(exclude[,cat]))))
    pp <- chisq.test(table(chiData[,1], chiData[,2]))$p.value
    comparison <- rbind(comparison, c(label(crvdata[,cat]),'','', round(pp,4)))
    for (lev in levels(crvdata[,cat])){
      comparison <- rbind(comparison, c(paste("--",lev ), 
                      paste(s <- sum(crvdata[,cat]==lev, na.rm=T), " (", round(s*100/is),
                            "%)", sep=""),
                      paste(s <- sum(exclude[,cat]==lev, na.rm=T), " (", round(s*100/xs),
                            "%)", sep=""),""))
    }
    next
  }
  anovaData <- as.data.frame(rbind(cbind(crvdata[,cat],rep("is", length(crvdata[,cat]))),
                     cbind(exclude[,cat],rep("xs", length(exclude[,cat])))))
  anovaData[,1] <- as.numeric(as.character(anovaData[,1]))
  pp <- kruskal.test(anovaData[,1] ~ anovaData[,2])$p.value
  comparison <- rbind(c(label(crvdata[,cat]), 
                paste(round(mean(crvdata[,cat], na.rm=T),1)," (",
                      round(sd(crvdata[,cat],na.rm=T),1), ")",sep=""),
                paste(round(mean(exclude[,cat], na.rm=T),1)," (",
                      round(sd(exclude[,cat],na.rm=T),1), ")",sep=""),
                round(pp,4)), comparison)
}
comparison <- as.data.frame(comparison[,c(1,3,2,4)])
colnames(comparison) <- c("Variable","Excluded", "Analyzed Data", "P-Value")
kable(comparison, width=3, 
      caption=paste("Comparison of Demographics for Excluded & Included Data, w/ N=",
                    length(exclude$map.id), " and N=",length(crvdata$map.id),
                                         " respectively", sep=""))



```



Missingness
```{r, echo=F}
#nrow(totalData)
#Start with 336
#nrow(crvdata)
#223 left after exclusions

missing <- c(c(), c())
#comparison[,c("Variable", "Analyzed Data")]
for (cat in cats){
    missing <- rbind(missing, c(label(crvdata[,cat]), paste(s <- sum(is.na(crvdata[,cat])), " (", round(s*100/is, 2), "%)", sep="")))          
 }   

missing <- as.data.frame(missing)
colnames(missing) <- c("Variable", "Missingness")

kable(missing, width=3, 
      caption=paste("Missingness (N=", nrow(crvdata), ")", sep=""))
```


```{r scatterplots,echo=F, fig.height=8, warning=F, message=F}
require(GGally)

predictors <- crvdata[,16:18]
outcomes <- crvdata[, 20:33]

outlong <- c()
for (out in names(outcomes)){
  lab <- rep(out, length(outcomes[,out]))
  temp <- cbind(outcomes[, out], lab, predictors)
  outlong <- rbind(outlong, temp)
}
names(outlong)[1] <- "outcome"
levels(outlong$lab) <- c("Left Hemisphere", "Right Hemisphere", "Left Frontal Lobe", 
                         "Right Frontal Lobe", "Full Frontal Lobe", "Left Occipital Lobe", 
                         "Right Occipital Lobe", "Full Occipital Lobe", "Left Temporal Lobe", 
                         "Right Temporal Lobe", "Full Temporal Lobe", "Left Parietal Lobe", 
                         "Right Parietal Lobe", "Full Parietal Lobe")

ggplot(outlong, aes(systolic.rising.surge, outcome, group=1)) +
  geom_point() + geom_smooth() + facet_wrap(~lab, ncol=3) + 
  theme(legend.position="none", strip.text = element_text(size=12), 
        axis.text.x = element_text(size=14), axis.text.y  = element_text(size=14),
        panel.grid.major.x=element_line(colour='grey')) +
  ylab("Measured CVR") + xlab("Systolic Rising Surge Blood Pressure")

ggplot(outlong, aes(systolic.prewaking.surge, outcome, group=1)) +
  geom_point() + geom_smooth() + facet_wrap(~lab, ncol=3) + 
  theme(legend.position="none", strip.text = element_text(size=12), 
        axis.text.x = element_text(size=14), axis.text.y  = element_text(size=14),
        panel.grid.major.x=element_line(colour='grey')) +
  ylab("Measured CVR") + xlab("Systolic Prewaking Surge Blood Pressure")


ggplot(outlong, aes(noc.sys.diff, outcome, group=1)) +
  geom_point() + geom_smooth() + facet_wrap(~lab, ncol=3) + 
  theme(legend.position="none", strip.text = element_text(size=12), 
        axis.text.x = element_text(size=14), axis.text.y  = element_text(size=14),
        panel.grid.major.x=element_line(colour='grey')) +
  ylab("Measured CVR") + xlab("Difference in Awake/Sleeping Systolic Blood Pressure")


```

```{r, boxplots, echo=F, warning=F, fig.height=4.5}
ggplot(outlong[1:1351,], aes(factor(lab), outcome)) +
  geom_boxplot(outlier.colour = "purple") + 
  theme(legend.position="none", strip.text = element_text(size=12), 
        axis.text.x = element_text(size=11, angle = 80, hjust = 1), 
        axis.text.y  = element_text(size=12),
        panel.grid.major.x=element_line(colour='grey')) +
  ylab("Measured CVR") + xlab("Area Scanned")

ggplot(outlong[1352:2701,], aes(factor(lab), outcome)) +
  geom_boxplot(outlier.colour = "purple") + 
  theme(legend.position="none", strip.text = element_text(size=12), 
        axis.text.x = element_text(size=11, angle = 70, hjust = 1), 
        axis.text.y  = element_text(size=14),
        panel.grid.major.x=element_line(colour='grey')) +
  ylab("Measured CVR") + xlab("Area Scanned")

```


```{r, imputation}
toPredict <- c("systolic.rising.surge", "systolic.prewaking.surge", 
               "noc.sys.diff")
imputeSR <- glm(systolic.rising.surge ~ enrolled.dx + sex + raceethnicity +
                apoe4pos + enrolled.dx + education + htnrx + icv + left.hemisphere + 
                right.hemisphere, data = crvdata)
pSysRising <- predict(imputeSR, newdata = crvdata)

imputeSP <- ols(systolic.prewaking.surge ~ enrolled.dx + sex + raceethnicity +
                apoe4pos + enrolled.dx + education + htnrx + icv + left.hemisphere + 
                right.hemisphere, data = crvdata)
pSysPrewaking <- predict(imputeSP, newdata = crvdata)

imputeNS <- ols(noc.sys.diff ~ enrolled.dx + sex + 
                  raceethnicity + apoe4pos + enrolled.dx + education + htnrx + icv +
                  left.hemisphere + right.hemisphere, data = crvdata)
pNocDiff <- predict(imputeNS, newdata = crvdata)

crvdata$sys.rising.impute <- NULL
crvdata$sys.prewaking.impute <- NULL
crvdata$noc.diff.impute <- NULL
for (i in 1:length(crvdata$map.id)){
  if (is.na(crvdata$systolic.rising.surge[i])){
    crvdata$sys.rising.impute[i] <- pSysRising[i]
  } else {crvdata$sys.rising.impute[i] <- crvdata$systolic.rising.surge[i]}
  if (is.na(crvdata$systolic.prewaking.surge[i])){
    crvdata$sys.prewaking.impute[i] <- pSysPrewaking[i]
  } else {crvdata$sys.rising.impute[i] <- crvdata$systolic.rising.surge[i]}
  if (is.na(crvdata$noc.sys.diff[i])){
    crvdata$noc.diff.impute[i] <- pNocDiff[i]
  } else {crvdata$noc.diff.impute[i] <- crvdata$systolic.rising.surge[i]}
}

plot(crvdata$systolic.rising.surge, pSysRising, pch=16, cex = .8, ylim=c(-25,45),
     main = "Imputed vs Empirical Data in Systolic Rising Surge", 
     xlab = "Empirical", ylab="Imputed")
abline(0,1, col='red', lwd=3)

plot(crvdata$systolic.prewaking.surge, pSysPrewaking, pch=16, cex = .8,
     main = "Imputed vs Empirical Data in Systolic Prewaking Surge", 
     xlab = "Empirical", ylab="Imputed")
abline(0,1)

plot(crvdata$noc.sys.diff, pNocDiff, pch=16, cex = .8,
     main = "Imputed vs Empirical Data in Nocturnal Difference in Systolic", 
     xlab = "Empirical", ylab="Imputed")
abline(0,1)


```
